USE itunes;
DROP TABLE IF EXISTS Tracks;
CREATE TABLE Tracks (
  trackId varchar(10) NOT NULL,
  wrapperType text,
  kind text,
  artistId text,
  collectionId text,
  artistName text,
  collectionName text,
  trackName text,
  collectionCensoredName text,
  trackCensoredName text,
  artistViewUrl text,
  collectionViewUrl text,
  trackViewUrl text,
  previewUrl text,
  artworkUrl30 text,
  artworkUrl60 text,
  artworkUrl100 text,
  collectionPrice text,
  trackPrice text,
  releaseDate text,
  collectionExplicitness text,
  trackExplicitness text,
  discCount text,
  discNumber text,
  trackCount text,
  trackNumber text,
  trackTimeMillis text,
  country text,
  currency text,
  primaryGenreName text,
  isStreamable text,
  creationDate timestamp default CURRENT_TIMESTAMP,
  PRIMARY KEY (trackId)
);
